export const currentUser = {
  id: 'user_1',
  email: 'demo@devstash.io',
  name: 'John Doe',
  isPro: false,
  createdAt: new Date('2025-01-15'),
  updatedAt: new Date('2025-01-15'),
};

export const itemTypes = [
  {
    id: 'type_snippet',
    name: 'Snippets',
    icon: 'Code',
    color: '#3b82f6',
    isSystem: true,
  },
  {
    id: 'type_prompt',
    name: 'Prompts',
    icon: 'Sparkles',
    color: '#a855f7',
    isSystem: true,
  },
  {
    id: 'type_command',
    name: 'Commands',
    icon: 'Terminal',
    color: '#22c55e',
    isSystem: true,
  },
  {
    id: 'type_note',
    name: 'Notes',
    icon: 'FileText',
    color: '#eab308',
    isSystem: true,
  },
  {
    id: 'type_file',
    name: 'Files',
    icon: 'File',
    color: '#94a3b8',
    isSystem: true,
  },
  {
    id: 'type_image',
    name: 'Images',
    icon: 'Image',
    color: '#ec4899',
    isSystem: true,
  },
  {
    id: 'type_url',
    name: 'Links',
    icon: 'Link',
    color: '#f97316',
    isSystem: true,
  },
];

export const collections = [
  {
    id: 'col_1',
    name: 'React Patterns',
    description: 'Common React patterns and hooks',
    isFavorite: true,
    itemCount: 12,
    userId: 'user_1',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-03-10'),
  },
  {
    id: 'col_2',
    name: 'Python Snippets',
    description: 'Useful Python code snippets',
    isFavorite: false,
    itemCount: 8,
    userId: 'user_1',
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-03-08'),
  },
  {
    id: 'col_3',
    name: 'Context Files',
    description: 'AI context files for projects',
    isFavorite: true,
    itemCount: 5,
    userId: 'user_1',
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-03-05'),
  },
  {
    id: 'col_4',
    name: 'Interview Prep',
    description: 'Technical interview preparation',
    isFavorite: false,
    itemCount: 24,
    userId: 'user_1',
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2025-03-12'),
  },
  {
    id: 'col_5',
    name: 'Git Commands',
    description: 'Frequently used git commands',
    isFavorite: true,
    itemCount: 15,
    userId: 'user_1',
    createdAt: new Date('2025-02-10'),
    updatedAt: new Date('2025-03-11'),
  },
  {
    id: 'col_6',
    name: 'AI Prompts',
    description: 'Curated AI prompts for coding',
    isFavorite: false,
    itemCount: 18,
    userId: 'user_1',
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-03-09'),
  },
];

export const items = [
  {
    id: 'item_1',
    title: 'useAuth Hook',
    contentType: 'text',
    content: 'Custom authentication hook for React applications',
    description: 'Custom authentication hook for React applications',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    userId: 'user_1',
    typeId: 'type_snippet',
    collectionId: 'col_1',
    tags: ['react', 'auth', 'hooks'],
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: 'item_2',
    title: 'API Error Handling Pattern',
    contentType: 'text',
    content: 'Fetch wrapper with exponential backoff retry logic',
    description: 'Fetch wrapper with exponential backoff retry logic',
    isFavorite: false,
    isPinned: true,
    language: 'typescript',
    userId: 'user_1',
    typeId: 'type_snippet',
    collectionId: 'col_1',
    tags: ['api', 'error-handling', 'fetch'],
    createdAt: new Date('2025-01-12'),
    updatedAt: new Date('2025-01-12'),
  },
  {
    id: 'item_3',
    title: 'Git Rebase Workflow',
    contentType: 'text',
    content: 'git fetch origin && git rebase origin/main',
    description: 'Clean rebase workflow for feature branches',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    userId: 'user_1',
    typeId: 'type_command',
    collectionId: 'col_5',
    tags: ['git', 'rebase', 'workflow'],
    createdAt: new Date('2025-02-10'),
    updatedAt: new Date('2025-02-10'),
  },
  {
    id: 'item_4',
    title: 'Code Review Prompt',
    contentType: 'text',
    content:
      'Review this code for security vulnerabilities, performance issues, and best practices.',
    description: 'Comprehensive code review prompt for AI assistants',
    isFavorite: true,
    isPinned: false,
    language: undefined,
    userId: 'user_1',
    typeId: 'type_prompt',
    collectionId: 'col_6',
    tags: ['ai', 'code-review', 'prompt'],
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-02-20'),
  },
  {
    id: 'item_5',
    title: 'Python List Comprehension Patterns',
    contentType: 'text',
    content: '[x for x in items if x.active]',
    description: 'Common list comprehension patterns in Python',
    isFavorite: false,
    isPinned: false,
    language: 'python',
    userId: 'user_1',
    typeId: 'type_snippet',
    collectionId: 'col_2',
    tags: ['python', 'list', 'patterns'],
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-02-15'),
  },
  {
    id: 'item_6',
    title: 'Docker Compose Cheatsheet',
    contentType: 'text',
    content: 'docker compose up -d --build',
    description: 'Essential Docker Compose commands',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    userId: 'user_1',
    typeId: 'type_command',
    collectionId: null,
    tags: ['docker', 'devops'],
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2025-03-01'),
  },
  {
    id: 'item_7',
    title: 'Meeting Notes Template',
    contentType: 'text',
    content:
      '# Meeting Notes\n\n## Date\n## Attendees\n## Agenda\n## Action Items',
    description: 'Reusable meeting notes markdown template',
    isFavorite: false,
    isPinned: false,
    language: 'markdown',
    userId: 'user_1',
    typeId: 'type_note',
    collectionId: null,
    tags: ['template', 'notes'],
    createdAt: new Date('2025-03-05'),
    updatedAt: new Date('2025-03-05'),
  },
  {
    id: 'item_9',
    title: 'System Design Interview Notes',
    contentType: 'text',
    content: '# System Design\n\n## Key Topics\n- Load balancing\n- Caching\n- Database sharding',
    description: 'Notes on system design interview topics',
    isFavorite: false,
    isPinned: false,
    language: 'markdown',
    userId: 'user_1',
    typeId: 'type_note',
    collectionId: 'col_4',
    tags: ['interview', 'system-design'],
    createdAt: new Date('2025-03-02'),
    updatedAt: new Date('2025-03-02'),
  },
  {
    id: 'item_10',
    title: 'Project Context Template',
    contentType: 'file',
    content: undefined,
    fileUrl: '/files/context-template.md',
    fileName: 'context-template.md',
    fileSize: 2048,
    description: 'Reusable AI context file template',
    isFavorite: false,
    isPinned: false,
    language: undefined,
    userId: 'user_1',
    typeId: 'type_file',
    collectionId: 'col_3',
    tags: ['context', 'template', 'ai'],
    createdAt: new Date('2025-01-22'),
    updatedAt: new Date('2025-01-22'),
  },
  {
    id: 'item_8',
    title: 'Tailwind Breakpoints Reference',
    contentType: 'text',
    content: 'sm: 640px, md: 768px, lg: 1024px, xl: 1280px, 2xl: 1536px',
    description: 'Quick reference for Tailwind CSS breakpoints',
    isFavorite: false,
    isPinned: false,
    language: undefined,
    userId: 'user_1',
    typeId: 'type_url',
    url: 'https://tailwindcss.com/docs/responsive-design',
    collectionId: null,
    tags: ['tailwind', 'css', 'reference'],
    createdAt: new Date('2025-03-08'),
    updatedAt: new Date('2025-03-08'),
  },
];

// Counts per item type for sidebar display
export const itemTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 3,
  type_url: 8,
};
